In [1]:
pip install tensorflow

Note: you may need to restart the kernel to use updated packages.


In [3]:
import tensorflow.compat.v1 as tf

In [5]:
tf.disable_eager_execution()

In [6]:
print(tf.__version__)

2.18.0


In [7]:
he = tf.constant("Hello")
wo = tf.constant("World")
hewo = he + wo
print(hewo)

Tensor("add:0", shape=(), dtype=string)


In [10]:
phe = "Hello "
pwo = "World"
phewo = phe + pwo
print(phewo)

Hello World


In [22]:
a = tf.constant(5)

In [23]:
b = tf.constant(2)

In [24]:
c = tf.constant(3)

In [25]:
d = tf.multiply(a, b)

In [26]:
e = tf.add(c, b)

In [27]:
f = tf.subtract(d, e)

In [28]:
sess = tf.Session()

In [29]:
res = sess.run(f)

In [30]:
sess.close()

In [33]:
print("Result={}".format(res))

Result=5


In [34]:
print(tf.get_default_graph())

In [35]:
g = tf.Graph()

In [36]:
print(g)

In [37]:
z = tf.constant(8)

In [38]:
print(z.graph is g)

False


In [39]:
print(z.graph is tf.get_default_graph())

True


In [40]:
sess = tf.Session()

In [41]:
fetches = [a, b, c, d, e, f]

In [42]:
res = sess.run(fetches)

In [43]:
sess.close()

In [44]:
print("Result={}".format(res))

Result=[5, 2, 3, 10, 5, 5]


In [45]:
a = tf.constant(3)

In [46]:
b = tf.Variable(6)

In [47]:
sum = tf.add(a, b)

In [48]:
sum = a+b

In [49]:
assign_value = tf.assign(b, 4)

In [50]:
# to change value of b
init_ops = tf.global_variables_initializer()

In [51]:
sess = tf.Session()

In [52]:
sess.run(init_ops)

In [53]:
print(sess.run(sum))

9


In [54]:
sess.run(assign_value)

4

In [55]:
print(sess.run(sum))

7


In [56]:
# placeholder
ph = tf.placeholder(tf.float32)

In [57]:
eqn = ph*2

In [58]:
sess.run(eqn, feed_dict={ph:4.0})

8.0

In [59]:
sess.run(eqn, feed_dict={ph:[1,2,3,4,5]})

array([ 2.,  4.,  6.,  8., 10.], dtype=float32)

In [61]:
sess.run(eqn, feed_dict={ph:[[1,2,3,4,5], [6,7,8,9,8], [7,3,2,1,0]]})

array([[ 2.,  4.,  6.,  8., 10.],
       [12., 14., 16., 18., 16.],
       [14.,  6.,  4.,  2.,  0.]], dtype=float32)

In [63]:
x = tf.placeholder(tf.float32)

In [64]:
y = tf.placeholder(tf.float32)

In [65]:
sum = x+y

In [66]:
prd = sum*5

In [67]:
sess = tf.Session()

In [69]:
sess.run(prd, feed_dict={x:[3], y:[4]})

array([35.], dtype=float32)